#' UMI4C Contacts Processing
#'
#' Using demultiplexed FastQ files as input, performs all necessary steps to end up with a tsv file summarizing the
#' restriction enzyme fragments and the number of UMIs supporting that specific contact with the viewpoint (bait) of
#' interest.
#'
#' @param fastq_dir Path of the directory containing the FastQ files (compressed or uncompressed).
#' @param wk_dir Working directory where to save the outputs generated by the UMI-4c analysis.
#' @param bait_seq Character containing the bait primer sequence.
#' @param bait_pad Character containing the pad sequence (sequence between the bait primer and the restriction enzyme sequence).
#' @param res_enz Character containing the restriction enzyme sequence.
#' @param cut_pos Numeric indicating the nucleotide position where restriction enzyme cuts (zero-based) (for example, for DpnII is 0).
#' @param digested_genome Path for the digested genome file generated using the \code{\link{digestGenome}} function.
#' @param ref_gen Path for the reference genome to use for the alignment (fasta format).
#' @param threads Number of threads to use in the analysis.
#' @param path_venv Path for the UMI4Cats virtual environment generated using the \code{\link{installVenv}}.
#' @param fastq_multx Path or character for calling the \code{fastq-multx} script to demultiplex reads.
#' @details This function is a combination of calls to other functions that perform the necessary steps for processing
#' UMI-4C data.
#' @examples
#' \dontrun{
#' contactsUMI4C(fastq_dir="raw_fastq",
#'               wk_dir="SOCS1",
#'               bait_seq="CCCAAATCGCCCAGACCAG",
#'               bait_pad="GCGCG",
#'               res_enz="GATC",
#'               cut_pos=0,
#'               digested_genome=hg19_dpnii,
#'               ref_gen="~/data/reference_genomes/hg19/hg19.fa",
#'               threads=1,
#'               path_venv="~/venvs/UMI4Cats_venv/",
#'               fastq_multx="fastq-multx")
#' }
#' @export
contactsUMI4C <- function(fastq_dir,
                          wk_dir,
                          bait_seq,
                          bait_pad,
                          res_enz,
                          cut_pos,
                          digested_genome,
                          ref_gen,
                          threads=1,
                          path_venv,
                          fastq_multx="fastq-multx"){

  dir.create(wk_dir, showWarnings=FALSE)
  cut_pos <- as.character(cut_pos) # convert to character

  prepR(path_venv = path_venv,
        fastq_dir = fastq_dir,
        wk_dir = wk_dir,
        bait_seq = bait_seq,
        bait_pad = bait_pad,
        res_enz = res_enz,
        fastq_multx = fastq_multx)

  splitR(path_venv = path_venv,
         wk_dir = wk_dir,
         res_enz = res_enz,
         cut_pos = cut_pos)

  alignmentR(path_venv = path_venv,
             wk_dir = wk_dir,
             threads = threads,
             ref_gen = ref_gen,
             bait_seq = bait_seq,
             bait_pad = bait_pad,
             res_enz = res_enz)

  umiCounterR(path_venv = path_venv,
              wk_dir = wk_dir,
              ref_gen = ref_gen,
              digested_genome = digested_genome,
              bait_seq = bait_seq,
              bait_pad = bait_pad,
              res_enz = res_enz)

  mergeUMICounter(digested_genome = digested_genome,
                  wk_dir = wk_dir,
                  bait_seq = bait_seq,
                  bait_pad = bait_pad,
                  res_enz = res_enz,
                  ref_gen = ref_gen)
}

#' Prepare UMI4C data
#'
#' Prepare the FastQ files for the analysis by selecting reads with bait and
#' adding the respective UMI identifier for each read in its header.
#' @inheritParams contactsUMI4C
#' @seealso \code{\link{contactsUMI4C}}
#' @examples
#' \dontrun{
#' prepR(fastq_dir="raw_fastq",
#'       wk_dir="SOCS1",
#'       bait_seq="CCCAAATCGCCCAGACCAG",
#'       bait_pad="GCGCG",
#'       res_enz="GATC",
#'       path_venv="~/venvs/UMI4Cats_venv/",
#'       fastq_multx="fastq-multx")
#'}
#'
#'@export
prepR <- function(fastq_dir,
                  wk_dir,
                  bait_seq,
                  bait_pad,
                  res_enz,
                  path_venv,
                  fastq_multx="fastq-multx") {

  reticulate::use_virtualenv(path_venv, required = TRUE)
  py_functions <- system.file("python/umi4cats.py", package = "UMI4Cats")
  reticulate::source_python(py_functions)

  prep(raw_dir = fastq_dir,
       wk_dir = wk_dir,
       bait_seq = bait_seq,
       bait_pad = bait_pad,
       res_e = res_enz,
       fastqmultx = fastq_multx)

}

#' Split UMI4C reads
#'
#' Split the prepared reads using the restrition enzyme information.
#' @inheritParams contactsUMI4C
#' @examples
#' \dontrun{
#' splitR(wk_dir="SOCS1",
#'        res_enz="GATC",
#'        cut_pos=0,
#'        path_venv="~/venvs/UMI4Cats_venv/")
#' }
#' @export

splitR <- function(wk_dir,
                   res_enz,
                   cut_pos,
                   path_venv){


  reticulate::use_virtualenv(path_venv, required = TRUE)
  py_functions <- system.file("python/umi4cats.py", package = "UMI4Cats")
  reticulate::source_python(py_functions)

  cut_pos <- as.character(cut_pos)

  split(wk_dir = wk_dir,
        res_e = res_enz,
        cut_pos = cut_pos)

}

#' UMI4C alignment
#'
#' Align splitted UMI-4C reads to a reference genome using Bowtie2.
#' @inheritParams contactsUMI4C
#' @examples
#' \dontrun{
#' alignmentR(wk_dir="SOCS1",
#'            bait_seq="CCCAAATCGCCCAGACCAG",
#'            bait_pad="GCGCG",
#'            res_enz="GATC",
#'            ref_gen="~/data/reference_genomes/hg19/hg19.fa",
#'            threads=1,
#'            path_venv="~/venvs/UMI4Cats_venv/")
#' }
#'
#' @export

alignmentR <- function(wk_dir,
                       bait_seq,
                       bait_pad,
                       res_enz,
                       ref_gen,
                       threads=1,
                       path_venv){

  reticulate::use_virtualenv(path_venv, required = TRUE)
  py_functions <- system.file("python/umi4cats.py", package = "UMI4Cats")
  reticulate::source_python(py_functions)

  # TODO: Move to {Rbowtie2} and {Rsamtools}
  bowtie2 <- "bowtie2"
  samtools <- "samtools"

  alignment(wk_dir = wk_dir,
            threads = threads,
            bowtie2 = bowtie2,
            ref_gen = ref_gen,
            samtools = samtools,
            bait_seq = bait_seq,
            bait_pad = bait_pad,
            res_e = res_enz)

}

#' UMI counting
#'
#' Algorithm for counting  and collapsing the number of UMIs supporting a specific ligation.
#' @inheritParams contactsUMI4C
#' @examples
#' \dontrun{
#' umiCounterR(wk_dir="SOCS1",
#'             bait_seq="CCCAAATCGCCCAGACCAG",
#'             bait_pad="GCGCG",
#'             res_enz="GATC",
#'             digested_genome=hg19_dpnii,
#'             ref_gen="~/data/reference_genomes/hg19/hg19.fa",
#'             path_venv="~/venvs/UMI4Cats_venv/")
#' }
#' @details For collapsing different molecules into the same UMI, takes into account the ligation position and
#' the number of UMI sequence mismatches.
#' @export

umiCounterR <- function(wk_dir,
                        bait_seq,
                        bait_pad,
                        res_enz,
                        digested_genome,
                        ref_gen,
                        path_venv){

  reticulate::use_virtualenv(path_venv, required = TRUE)
  py_functions <- system.file("python/umi4cats.py", package = "UMI4Cats")
  reticulate::source_python(py_functions)

  bowtie2 <- "bowtie"
  samtools <- "samtools"

  umiCounter(wk_dir = wk_dir,
             bowtie2 = bowtie2,
             ref_gen = ref_gen,
             samtools = samtools,
             genomic_track = digested_genome,
             bait_seq = bait_seq,
             bait_pad = bait_pad,
             res_e = res_enz)

}


#' Merge UMI4C counts
#'
#' Merge UMI4C counts with digested genome framgment position, returning all fragments and UMIs
#' 10Mb around the viewpoint.
#' @inheritParams contactsUMI4C
#' @examples
#' \dontrun{
#' mergeUMICounter(wk_dir="SOCS1",
#'                 digested_genome=hg19_dpnii,
#'                 bait_seq="CCCAAATCGCCCAGACCAG",
#'                 bait_pad="GCGCG",
#'                 res_enz="GATC",
#'                 ref_gen="~/data/reference_genomes/hg19/hg19.fa")
#' }
#' @export
mergeUMICounter <- function(digested_genome,
                            wk_dir,
                            bait_seq,
                            bait_pad,
                            res_enz,
                            ref_gen){

  bowtie2 <- 'bowtie2'

  counts_path <- file.path(wk_dir, 'rst')

  umi_files <- list.files(counts_path,
                                 full.names = T,
                                 pattern = '\\_umi_counts.tsv$')


  counts_path <- file.path(wk_dir, 'rst')

  for(umis in umi_files){

    file_name <- gsub("\\..*$", "", basename(umis))

    df_umis <- read.table(umis)

    df_umis <- data.frame(lapply(df_umis, as.character), stringsAsFactors=FALSE)

    colnames(df_umis) <- c('chr_bait', 'pos_bait', 'chr_contact', 'pos_contact', 'UMIs')

    df_dig_genome <- read.table(digested_genome, stringsAsFactors = F)

    # get coordinates of viewpoint using bowtie2
    viewpoint <- paste0(bait_seq, bait_pad, res_enz)

    index <- gsub('\\..*$', '', ref_gen)

    viewpointPos <- system(paste("bowtie2 --quiet",
                                 "-x", index,
                                 "-c", viewpoint,
                                 "-N 0",
                                 "| samtools view",
                                 "| awk \'{print $3,$4}\'"),
                           intern = T)

    viewpointPos <- unlist(strsplit(viewpointPos, " "))
    chrVP <- viewpointPos[1]
    startVP <- as.numeric(viewpointPos[2])

    start10M <- startVP - 10e6
    end10M <- startVP + 10e6

    sub_df_dig_genome <- df_dig_genome[(df_dig_genome$V1 == chrVP) &
                                          (df_dig_genome$V2 >= start10M) &
                                          (df_dig_genome$V2 <= end10M),]

    sub_df_dig_genome <- sub_df_dig_genome[c(1,2)]

    colnames(sub_df_dig_genome)[1:2] <- c('chr_contact', 'pos_contact')

    sub_df_dig_genome <- data.frame(lapply(sub_df_dig_genome, as.character), stringsAsFactors=FALSE)

    df_umi_10M <- dplyr::left_join(sub_df_dig_genome, df_umis)
    df_umi_10M$UMIs[is.na(df_umi_10M$UMIs)] <- 0
    df_umi_10M$chr_bait[is.na(df_umi_10M$chr_bait)] <- unique(df_umis$chr_bait)
    df_umi_10M$pos_bait[is.na(df_umi_10M$pos_bait)] <- unique(df_umis$pos_bait)


    df_umi_10M <- df_umi_10M[,c('chr_bait', 'pos_bait', 'chr_contact', 'pos_contact', 'UMIs')]

    umi_output <- file.path(wk_dir, 'rst', paste0(file_name, '_counts10M.tsv'))

    write.table(x = df_umi_10M,
                file = umi_output,
                row.names = F,
                quote = F,
                sep = '\t')
  }
}

