#' Differential UMI4C contacts using Fisher's Exact test
#'
#' @param umi4c UMI4C object as generated by \code{makeUMI4C} or the \code{UMI4C} constructor.
#' @param grouping Name of the \code{colData(UMI4C)} column that will be used for grouping the UMI4C profiles
#' and performing differential analyses.
#' @param query_regions \code{GenomicRanges} object containing the coordinates for the regions where to
#' perform the differential analysis.
#' @param resize Width in base pairs for resizing the query regions. Default: no resizing.
#' @param padj_method Method for adjusting p-values. See \code{\link[stats]{p.adjust}} for the different methods.
#' @export
fisherUMI4C <- function(umi4c,
                        grouping="condition",
                        query_regions,
                        resize=NULL,
                        padj_method="fdr") {
  factor <- unique(colData(umi4c)[, grouping])

  if (length(factor)!=2) stop("Incorrect 'grouping' variable, it should divide your data in two groups.")

  ids_ref <- colData(umi4c)$sampleID[grep(factor[1], colData(umi4c)[,grouping])]
  ids_cond <- colData(umi4c)$sampleID[grep(factor[2], colData(umi4c)[,grouping])]

  row_ranges <- rowRanges(umi4c)
  umis <- assays(umi4c)$umis

  # umis <- umis*assays(umi4c)$norm_mat

  row_ranges$umis_ref <- rowSums(umis[,ids_ref, drop=FALSE])
  row_ranges$umis_cond <-  rowSums(umis[,ids_cond, drop=FALSE])

  total_ref <- sum(row_ranges$umis_ref, na.rm=TRUE)
  total_cond <- sum(row_ranges$umis_cond, na.rm=TRUE)

  # Resize query regions if value provided
  if(!is.null(resize)) query_regions <- GenomicRanges::resize(query_regions,
                                                              width=resize,
                                                              fix="center")

  # Find overlaps between fragment ends and query regions
  ols <- GenomicRanges::findOverlaps(row_ranges, query_regions)

  # Sum UMIs
  fends_split <- split(mcols(row_ranges)[queryHits(ols),], query_regions$id[subjectHits(ols)])
  fends_summary <- lapply(fends_split,
                          function(x) data.frame(umis_ref=sum(x$umis_ref),
                                                 umis_cond=sum(x$umis_cond)))
  fends_summary <- do.call(rbind, fends_summary)
  fends_summary$query_id <- names(fends_split)

  mat_list <- lapply(1:nrow(fends_summary), function(x) matrix(c(as.vector(t(fends_summary[1,1:2])),
                                                                 total_ref, total_cond),
                                                               ncol=2,
                                                               dimnames=list(c("ref", "cond"),
                                                                             c("query", "region"))))

  fends_summary$pval <- unlist(lapply(mat_list, function(x) fisher.test(x)$p.value))
  fends_summary$odds_ratio <- unlist(lapply(mat_list, function(x) fisher.test(x)$estimate))
  fends_summary$padj <- p.adjust(fends_summary$pval, method=padj_method)

  return(fends_summary)
}
