#' Digest reference genome
#'
#' Performs an \emph{in silico} digestion of a given reference genome using a given restriction enzyme sequence.
#' @param res_enz Character containing the restriction enzyme sequence.
#' #' @param cut_pos Numeric indicating the nucleotide position where restriction enzyme cuts (zero-based) (for example, for DpnII is 0).
#' @param name_RE Restriction enzyme name .
#' @param ref_gen A BSgenome object of the reference genome.
#' @param out_path Output path where to save the genomic track. The default is a directory named \code{digested_genome/}
#' created in your working directory.
#' @return Creates a tab-delimited file in \code{out_path} named "\code{ref_gen_name_RE.tsv}", containing the
#' coordinates for all fragments generated by digesting the genome using the given cutting sequences.
#' @examples
#' \dontrun{
#' library(BSgenome.Hsapiens.UCSC.hg19)
#' ref_gen <- BSgenome.Hsapiens.UCSC.hg19
#'
#' hg19_dpnii <- digestGenome(res_enz="GATC",
#'                            cut_pos=0
#'                            name_RE="DpnII",
#'                            ref_gen=ref_gen,
#'                            out_path="digested_genome/")
#'}
#' @export
digestGenome <- function(res_enz,
                         cut_pos,
                         name_RE,
                         ref_gen,
                         out_path="digested_genome/"){

  message(paste("Generating digested genome using:\n",
                "> Restriction enzyme sequence:", res_enz, "\n",
                "> Restriction enzyme cut position:", cut_pos, "\n",
                "> Restriction enzyme name:", name_RE, "\n",
                "> Reference genome:", GenomeInfoDb::bsgenomeName(ref_gen), "\n",
                "> Output path:", out_path))

  cut_seq_5p <- substr(res_enz, 0, cut_pos)
  cut_seq_3p <- substr(res_enz, cut_pos + 1, nchar(res_enz))
  cp5p <- nchar(cut_seq_5p)
  cp3p <- nchar(cut_seq_3p)

  # TODO: Include RE database, given RE name use info on cutting sequence.
  # TODO: Deal with restriction enzymes that have Ns or positions with multiple nucleotide options

  # Identify the recongnition sites for each chromosomal entry
  genome_track <- data.frame()

  for (chr in seq_along(ref_gen)){
    # Find pattern in chr
    matches <- Biostrings::matchPattern(res_enz, ref_gen[[chr]])
    temp_df <- data.frame(chr = seqnames(ref_gen)[[chr]],
                          start = start(GenomicRanges::gaps(matches)) - cp3p,
                          end = end(Biostrings::gaps(matches)) + cp5p) # add re nucleotide length
    temp_df$start[temp_df$start<0] <- 1
    temp_df$end[temp_df$end>length(ref_gen[[chr]])] <- length(ref_gen[[chr]])

    genome_track <- rbind(genome_track,
                          temp_df)
  }

  # Save digested genome
  dir.create(out_path, showWarnings = FALSE) # Create directory if it doesn't exist
  out_track <- file.path(out_path, paste0(GenomeInfoDb::bsgenomeName(ref_gen), "_", name_RE, '.tsv'))

  write.table(genome_track,
              out_track,
              col.names = FALSE,
              row.names = FALSE,
              quote = FALSE,
              sep = "\t")

  message(paste("Finished genome digestion."))

  # Return path of the digested genome invisibly
  invisible(out_track)
}
