#' Digest reference genome
#'
#' Performs an \emph{in silico} digestion of a given reference genome using a given restriction enzyme sequence.
#' @param res_enz Character containing the restriction enzyme sequence.
#' #' @param cut_pos Numeric indicating the nucleotide position where restriction enzyme cuts (zero-based) (for example, for DpnII is 0).
#' @param name_RE Restriction enzyme name .
#' @param ref_gen A BSgenome object of the reference genome.
#' @param out_path Output path where to save the genomic track. The default is a directory named \code{digested_genome/}
#' created in your working directory.
#' @return Creates a tab-delimited file in \code{out_path} named "\code{ref_gen_name_RE.tsv}", containing the
#' coordinates for all fragments generated by digesting the genome using the given cutting sequences.
#' @examples
#' \dontrun{
#' library(BSgenome.Hsapiens.UCSC.hg19)
#' ref_gen <- BSgenome.Hsapiens.UCSC.hg19
#'
#' hg19_dpnii <- digestGenome(res_enz="GATC",
#'                            cut_pos=0,
#'                            name_RE="DpnII",
#'                            ref_gen=ref_gen,
#'                            out_path="digested_genome/")
#'}
#' @export
digestGenome <- function(res_enz,
                         cut_pos,
                         name_RE,
                         ref_gen,
                         out_path="digested_genome/"){

  message(paste("Generating digested genome using:\n",
                "> Restriction enzyme sequence:", res_enz, "\n",
                "> Restriction enzyme cut position:", cut_pos, "\n",
                "> Restriction enzyme name:", name_RE, "\n",
                "> Reference genome:", GenomeInfoDb::bsgenomeName(ref_gen), "\n",
                "> Output path:", out_path))
  # TODO: Include RE database, given RE name use info on cutting sequence.
  # TODO: Deal with restriction enzymes that have Ns or positions with multiple nucleotide options

  # Identify the recongnition sites for each chromosomal entry
  genome_track <- data.frame()

  for (chr in seq(ref_gen)){

    sel_gen <- ref_gen[[chr]]

    # Find pattern in chr
    matches <- Biostrings::matchPattern(res_enz, sel_gen)
    IRanges::start(matches) <- IRanges::start(matches) - 1
    IRanges::end(matches) <- IRanges::end(matches) - (nchar(res_enz) - cut_pos)

    gaps <- Biostrings::gaps(matches, start=1, end=length(sel_gen))

    temp_df <- data.frame(chr=GenomeInfoDb::seqnames(ref_gen)[chr],
                          start=IRanges::start(gaps),
                          end=IRanges::end(gaps))

    genome_track <- rbind(genome_track,
                          temp_df)
  }

  genome_track$id <- paste0("fragment_", name_RE, "_", 1:nrow(genome_track))

  # Save digested genome
  dir.create(out_path, showWarnings = FALSE) # Create directory if it doesn't exist
  out_track <- file.path(out_path, paste0(GenomeInfoDb::bsgenomeName(ref_gen), "_", name_RE, '.tsv'))

  write.table(genome_track,
              out_track,
              col.names = FALSE,
              row.names = FALSE,
              quote = FALSE,
              sep = "\t")

  message(paste("Finished genome digestion."))

  # Return path of the digested genome invisibly
  invisible(out_track)
}
