#' Umi4c umiCount
#'
#' This function relates the segments of reads generated in the split phase with the fragments of a defined genome track 
#' (which can be generated by genomicTrackGenerator.R), and counts the number of UMIs for every contact.
#'
#' @inheritParams umi4CatsContacts
#' @export
#' 
umiCounter <- function(wk_dir,
                        cores,
                        bait_seq,
                        bait_pad,
                        re,
                        ref_gen,
                        genomic_track,
                        bowtie2="bowtie2"){
  # run prep script
  umi_counter_script <- system.file("exec/umiCounter.sh", package = "UMI4Cats")
  system(paste(umi_counter_script,
               "-w", wk_dir,
               "-c", cores,
               "-s", bait_seq,
               "-p", bait_pad,
               "-r", re,
               "-i", ref_gen,
               "-f", genomic_track,
               "-b", bowtie2))
  
}